name: Deployment Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create application files
        run: |
          mkdir -p dist
          echo "<html><head><title>Task Manager</title></head><body><h1>Task Management Application</h1><p>Deployed via GitHub Actions</p></body></html>" > dist/index.html
          echo "Application files created successfully"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          if-no-files-found: error

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    if: github.event_name == 'push' || github.event.inputs.environment == 'staging'
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment"
          ls -la
          echo "Staging deployment completed"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.event.inputs.environment == 'production'
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Deploy to production
        run: |
          echo "Deploying to production environment"
          ls -la
          echo "Production deployment completed"
